pool:
  name: Default
  demands:
  - Agent.OS -equals linux
  - Agent.OSArchitecture -equals ARM64
trigger:
- buildbranch_linux_aarch64
pr: none
stages:
- stage: stage_0
  jobs:
  - job: ros_noetic_velodyne_description_ros_noetic_velodyne_gazebo_plugins_ros_noetic_velodyne_simulator
    steps:
    - script: |-
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-velodyne-description ros-noetic-velodyne-gazebo-plugins
          ros-noetic-velodyne-simulator
        DOCKER_IMAGE: condaforge/linux-anvil-aarch64
      displayName: Build ros-noetic-velodyne-description ros-noetic-velodyne-gazebo-plugins
        ros-noetic-velodyne-simulator
