package:
  name: ros-noetic-velodyne-gazebo-plugins
  version: 1.0.11
source:
  git_url: https://github.com/DataspeedInc-release/velodyne_simulator-release.git
  git_rev: release/noetic/velodyne_gazebo_plugins/1.0.11-1
  folder: ros-noetic-velodyne-gazebo-plugins/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-catkin
    - ros-noetic-gazebo-ros
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
  run:
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-gazebo-ros
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
